import 'package:flutter/widgets.dart';
import 'package:redux_comp/models/user_models/consumer_model.dart';
import 'models/error_type_model.dart';
import 'models/user_model.dart';

@immutable
class AppState {
  // put all app state requiered here
  final UserModel? user; // autogenerated user id from amplify
  final bool signUpComplete;
  final ErrorType error;

  // constructor must only take named parameters
  const AppState({
    required this.user,
    required this.signUpComplete,
    required this.error,
  });

  // this methods sets the starting state for the store
  factory AppState.initial() {
    return const AppState(
      user: null,
      signUpComplete: false,
      error: ErrorType.none,
    );
  }

  factory AppState.mock() {
    return const AppState(
      user: ConsumerModel("0", "name", "some@email.com"),
      signUpComplete: false,
      error: ErrorType.none,
    );
  }

  // easy way to replace store wihtout specifying all paramters
  AppState replace({
    UserModel? user,
    bool? signUpComplete,
    ErrorType? error,
  }) {
    return AppState(
      user: user ?? this.user,
      signUpComplete: signUpComplete ?? this.signUpComplete,
      error: error ?? this.error,
    );
  }
}
