#This file serves as "central point" where everything is called from
name: CI TESTS

on:
  pull_request:
    branches: [develop]
  #Manual workflow trigger to run analyze and test
  workflow_dispatch:
    inputs:
      testChoice:
        type: choice
        description: 'Test Type'
        required: true
        options: 
        - all
        - affected

#Only execute without cache when it comes to checking PR's
#Too many errors slipping through with cache
jobs:
  test-all:
    uses: ./.github/workflows/android.yml
    if: ${{github.event.inputs.testChoice == 'all' || github.event.inputs.testChoice == ''}}
    with:
      test: 'all'